### ISSUE TITLE
Toast通知 不会适应屏幕

### ISSUE THREAD

**Issue by qjebbs** [ismartjs/ismartjs#2]
如在手机上使用，内容就跑出屏幕外了。

ismartjs真的不错，感谢你的贡献。

**Comment by CTOSPACE** [comment]
ok，这个问题修复一下。但是ismartjs其实并没有做手机适配的。但是做了pad适配，toast可以适配下手机

**Comment by CTOSPACE** [comment]
问题已经修复，现在在小屏下toast通知会居中显示，宽度为页面宽度的80%
