### ISSUE TITLE
有没有可能提供一种选项，不在页面内管理tab

### ISSUE THREAD

**Issue by qjebbs** [ismartjs/ismartjs#3]
因为页面内开一堆tab，一刷新就只剩当前这一个了。或者经常习惯性 ctrl+w 关了整个页面。

**Comment by CTOSPACE** [comment]
最近正在计划写一个单页的布局，不知道能不能符合你的需求，可以加我qq175309744，提一下你的具体需求。

**Comment by qjebbs** [comment]
不好意思，最近比较忙。
目前为止，个人感觉在需求上略有不满足的几个点，都不是开发过程中的问题，而是后台完成后，使用者体验的问题。
这里在归纳一下，如果后面有想到其他的再补充：

1. 现有多tab结构，刷新与关闭整个页面的问题，就是上面描述的。
1. 如果不是单页多tab结构了。链接希望是html普通链接的定义，因为需要“右键-新窗口打开”。我看到页面内部开发是可以用href定义的，希望框架层面也偏向于这样的做法。目前，像左边栏的主菜单，用的是js，不支持新页面这种动作。这个对提升后台操作效率是很有意义的。
1. 页面间的tab有第一条说的问题，页面内部开发tab我却希望被框架接管。希望有方便的组件或api可以开发页面内的tab。并且tab的激活状态会反映在链接中，比如：`http://domain/admin/#html/user.html?id=1&tab=1`。现有框架要实现这个目的要自行编写tab的激活切换。之所以提这个需求，是因为这样的链接方式能够直达用户操作所在的页面，对于内部交换信息非常有帮助。因为我们肯定不喜欢这样：“页面的链接是这个，打开后再点击tab 1，才是我要让你看的。”

**Comment by CTOSPACE** [comment]
1、现在刷新后，会默认加载刷新之前处于打开状态的tab。
2、如果不是多tab结构，那么主界面区域就只能打开一个窗口，右键打开新窗口这个想法很不错，没有打开新窗口的功能因为之前设计思想就是通过页面内tab去管理打开的页面，而且打开新窗口整个框架的初始化是有点慢的，因为要按序加载很多东西。所以右键打开新窗口的也只能是及少量的操作。页面内部如果定义<a href='' external target="_blank"></a>的话，就是打开新窗口，用external表明是外部的链接，框架就会忽略。
3、页面内tab在我们现有项目中有很多应用，但是没有控件化，因为还没有想好如何去控件化页面内的tab功能，我贴个示例：
`<ul class="nav nav-tabs nav-justified" id="nav">
        <li class="active" data-href="/order/orders.html">
            <a href="javascript:;">所有</a>
        </li>
        <li data-href="/order/orders.html?status=WAIT_VERIFY">
            <a href="javascript:;">待审核<span class="status-num" data-status="WAIT_VERIFY">(0)</span></a>
        </li>
        <li data-href="/order/orders.html?status=WAIT_DELIVER">
            <a href="javascript:;">待发货<span class="status-num" data-status="WAIT_DELIVER">(0)</span></a>
        </li>
        <li data-href="/order/orders.html?status=DELIVERING">
            <a href="javascript:;">已发货<span class="status-num" data-status="DELIVERING">(0)</span></a>
        </li>
        <li data-href="/order/orders.html?status=WAIT_CANCEL">
            <a href="javascript:;">待取消<span class="status-num" data-status="WAIT_CANCEL">(0)</span></a>
        </li>
    </ul>
    <div id="contentPanel" s="window"  s-window="{href: '/order/orders.html'}"></div>
<script type="text/javascript">
   $nav.node.delegate("li", 'click', function (e) {
          var li = $(e.currentTarget);
           var href = li.attr("data-href");
          $contentPanel.load(href);
          li.addClass("active").siblings(".active").removeClass("active");
     });
</script>
`
这个就是我们现在常用的页面内tab的处理方式，代码量不多。
不过页面内tab没有状态保存，这个会随后实现，很不错的想法。

**Comment by qjebbs** [comment]
谢谢详细的回复。那么先把这个问题关了:)
