### ISSUE TITLE
表单验证问题

### ISSUE THREAD

**Issue by qjebbs** [ismartjs/ismartjs#4]
假设我有一个input是这个写的：

```html
<input s type="text" class="form-control" name="Email" s-valid-error="email()"/>
```

如果我输入为空，他提示我是格式不正确的。也就是`eamil()`兼具了`require()`的功效。这似乎是不对的。

**Comment by CTOSPACE** [comment]
需要加个require(false),email()，这样写就可以了

**Comment by qjebbs** [comment]
soga. 虽然不符合直觉，但问题解决了
